@startuml 
 scale max 1080 width
left to right direction 
[<b>Theme.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Config.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>styles.js</b>\n\n<i> </i>\n\n<i>error </i>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>args.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>Commenting.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Body.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>ChromeStorage.js</b>\n\n<i>items </i>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>HypothesisBackgroundManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>GoogleSheetClient.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>TextSummary.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Alerts.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>TextSummary.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>PDF.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>TextSummary.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>reviewModel.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>AnnotationServer.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>ExportCodebook.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>ExportCodebookJSON.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>HTML.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>AnnotationUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>RenameCodebook.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>BrowserStorageClient.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>RandomUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>TXT.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>HypothesisManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>HypothesisClientManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>HypothesisManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>HypothesisBackgroundManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>HypothesisManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>HypothesisManagerOAuth.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>test.js</b>\n\n<i> </i>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>Screenshots.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Alerts.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>Screenshots.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>PDF.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>Screenshots.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>MoodleClientManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>Screenshots.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>AnnotatedFileGeneration.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>GoogleSheetsManager.js</b>\n\n<i>token </i>\n Uses Feature:GoogleSheetConsumer\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>GoogleSheetClient.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>scienceDirectContentScript.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>URLUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>scienceDirectContentScript.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Config.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>AnnotationList.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>NoCodebook.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>Toolset.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>Neo4JClientManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>AnnotationServerManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>Neo4JClientManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Alerts.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>Neo4JClientManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Neo4JClient.js</b>\n\n<i>initializeGraph err, response </i>\n\n<i>descapalo data</i>\n\n<i>debuggingg msg, priority </i>\n\n<i>apiCall settings, callback </i>\n\n<i>escapalo data</i>\n\n<i>isString value </i>\n\n<i>escapify myJSON </i>\n\n<i>doNothing  }</i>\n\n<i>commitNeo4J query, callback </i>\n\n<i>sleep miliseconds </i>\n\n<i>traverse o </i>\n\n<i>randomString length = 17, charSet </i>\n\n<i>cypherRDFNeo4J cypher, callback </i>\n\n<i>getObjectId data, id </i>\n\n<i>apiCallJSON settings, callback </i>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>MoodleFunctions.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>MoodleClient.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>DataUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>LanguageUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>SheetUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>MoodleClient.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>ReplyAnnotation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>AnnotationUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>ReplyAnnotation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Config.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>MoodleGraderAugmentation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>MoodleScraping.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>Alerts.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>DOM.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>SuggestingLiterature.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Body.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>DeleteGroup.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>AnnotatedContentManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Events.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>acmContentScript.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>URLUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>acmContentScript.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Config.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>MoodleViewPluginAssignSubmissionAugmentation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>MoodleScraping.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>UpdateCodebook.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Theme.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>MoodleAugmentation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>MoodleGradingAugmentation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>MoodleAugmentation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>MoodleGraderAugmentation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>MoodleAugmentation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>MoodleViewPluginAssignSubmissionAugmentation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>Events.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>AnnotationManagement.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>ReadAnnotation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>AnnotationManagement.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>CreateAnnotation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>AnnotationManagement.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>UpdateAnnotation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>AnnotationManagement.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>DeleteAnnotation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>AnnotationManagement.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>RolesManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>AnnotationManagement.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>PDF.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>AnnotationManagement.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Events.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>AnnotationManagement.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Classifying.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>AnnotationManagement.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Annotation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>AnnotationServerManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>ChromeStorage.js</b>\n\n<i>items </i>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>AnnotationServerManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Config.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>pages.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>args.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>popup.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>BrowserStorage.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>AnnotationServer.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>ReadAnnotation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>DOMTextUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>Neo4JManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>ChromeStorage.js</b>\n\n<i>items </i>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>viewer.js</b>\n\n<i>  </i>\n\n<i>createTextLayerBuildertextLayerDiv, pageIndex, viewport </i>\n\n<i>PDFLinkService </i>\n\n<i>downloadUrlurl, filename </i>\n\n<i>webViewerWheelevt </i>\n\n<i>setTextContenttextContent </i>\n\n<i>setPageLabellabel </i>\n\n<i>evalStringtext </i>\n\n<i>paintOnCanvascanvasWrapper </i>\n\n<i>resolve </i>\n\n<i>attachDOMEventsToEventBuseventBus </i>\n\n<i>updateUIResultsCount </i>\n\n<i>data </i>\n\n<i>renderPages </i>\n\n<i>exception </i>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>locales.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>args.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>elementIsInVariant.js</b>\n\n<i>initvdm, models, variables, parameter </i>\n\n<i>writeElementLinesfw, element </i>\n\n<i>done </i>\n\n<i>writelinefw, line </i>\n\n<i>work </i>\n\n<i>exportModelsmodels </i>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>pdf.js</b>\n\n<i>setupFakeWorkerGlobal </i>\n\n<i>PDFObjects_ensureObjobjId </i>\n\n<i>validateit </i>\n\n<i>ReadableByteStreamControllerRespondInternalcontroller, bytesWritten </i>\n\n<i>PDFNetworkStreamFullRequestReader_onDoneargs </i>\n\n<i>PDFDocumentProxypdfInfo, transport, loadingTask </i>\n\n<i>PDFDocumentProxy_getPagepageNumber </i>\n\n<i>checkInputTypeNumberAssign </i>\n\n<i>o, p, v </i>\n\n<i>CanvasGraphics_beginInlineImage </i>\n\n<i>PageViewportClosure </i>\n\n<i>getWorkerSrc </i>\n\n<i>CanvasGraphics_paintSolidColorImageMask </i>\n\n<i>target, iterable </i>\n\n<i>ReadableByteStreamControllerRespondWithNewViewcontroller, view </i>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>ImportCodebookJSON.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Codebook.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>HypothesisClientInterface.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>Buttons.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>hypothesisGroupContentScript.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>ChromeStorage.js</b>\n\n<i>items </i>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>hypothesisGroupContentScript.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>HypothesisClientManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>MoodleClientManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>MoodleClient.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>MoodleClientManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>MoodleFunctions.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>MoodleClientManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>APISimulation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>MoodleClientManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Config.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>Code.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Config.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>Code.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>LanguageUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>Sidebar.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>AnnotationImporter.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Alerts.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>AnnotationImporter.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>FileUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>AnnotationImporter.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Codebook.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>options.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>ColorUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>reviewModel.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Config.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>moodleContentScript.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>MoodleProvider.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>moodleContentScript.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>MoodleAugmentation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>args.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>MoodleProvider.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>Assessing.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Body.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>HypothesisManagerOAuth.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>version.js</b>\n\n<i>inc importance </i>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>clean.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>args.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>GoogleSheetsClientManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>GoogleSheetClient.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>GoogleSheetsClientManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Alerts.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>CreateAnnotation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Events.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>CreateAnnotation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>LanguageUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>CreateAnnotation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Alerts.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>CreateAnnotation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Annotation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>CreateAnnotation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>DOMTextUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>CreateAnnotation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>PDFTextUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>CreateAnnotation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>PDF.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>CommentingForm.js</b>\n\n<i> </i>\n\n<i>request, response </i>\n\n<i>data </i>\n\n<i>event, ui </i>\n\n<i>e </i>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Alerts.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>ModeManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>LanguageUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>ModeManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Events.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>manifest.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>applyBrowserPrefixesFor.js</b>\n\n<i>applyBrowserPrefixesFor _vendor </i>\n\n<i>iterator obj </i>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>manifest.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>args.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>APISimulation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>DOM.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>GroupSelector.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Alerts.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>GroupSelector.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>ChromeStorage.js</b>\n\n<i>items </i>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>GroupSelector.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>LanguageUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>PreviousAssignments.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Config.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>PreviousAssignments.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Codebook.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>ContentScriptManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>TargetManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>ContentScriptManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Sidebar.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>ContentScriptManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>CodebookManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>ContentScriptManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Config.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>ContentScriptManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>AnnotationBasedInitializer.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>CryptoUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>EmptyCodebook.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>Popup.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>pdf.worker.js</b>\n\n<i>validateit </i>\n\n<i>extendbuffer, offset, size </i>\n\n<i>isOpenTypeFilefile </i>\n\n<i>PageViewportClosure </i>\n\n<i>getUshortdata, offset </i>\n\n<i>XRef_fetchIfRefobj, suppressEncryption </i>\n\n<i>fn, args, that </i>\n\n<i>resolve </i>\n\n<i>_Annotation10 </i>\n\n<i>PartialEvaluator_extractDataStructuresdict, baseDict, properties </i>\n\n<i>RadialAxial_getIR </i>\n\n<i>data </i>\n\n<i>readUint16 </i>\n\n<i>Type1Parserstream, encrypted, seacAnalysisEnabled </i>\n\n<i> </i>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>DeleteAnnotation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Events.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>DeleteAnnotation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>LanguageUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>DeleteAnnotation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Alerts.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>MoodleGradingAugmentation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>MoodleScraping.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>DateTimeUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>googleSheetsContentScript.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>GSheetProvider.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>pack.js</b>\n\n<i>getPackFileType  </i>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>args.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>GSheetProvider.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>GSheetParser.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>GSheetProvider.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>GroupInitializer.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>Options.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Alerts.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>Body.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>TargetManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Events.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>MoodleReport.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>MoodleClientManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>MoodleReport.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>MoodleUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>MoodleReport.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Alerts.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>MoodleReport.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Config.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>MoodleReport.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Events.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>MoodleReport.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Commenting.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>MoodleReport.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>APISimulation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>Config.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>GSheetParser.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>fonts.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>args.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>index.js</b>\n\n<i>reqListener  </i>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>BackToWorkspace.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>RolesManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>gulpfile.babel.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>GoogleSheetGenerator.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Alerts.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>GoogleSheetGenerator.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>AnnotationUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>GoogleSheetGenerator.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>LanguageUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>GoogleSheetGenerator.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Config.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>GoogleSheetGenerator.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Theme.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>MoodleEstimation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>AnnotationUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>MoodleEstimation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Codebook.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>moodleEstimation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>HypothesisClientManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>moodleEstimation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>BrowserStorageManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>moodleEstimation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>DateTimeUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>moodleEstimation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>MoodleEstimation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>DOMTextUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>DOM.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>DOMTextUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>LanguageUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>DOMTextUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>dom-anchor-text-quote.js</b>\n\n<i>toRange root, selector, options = } </i>\n\n<i>fromTextPosition root, selector </i>\n\n<i>fromRange root, range </i>\n\n<i>toTextPosition root, selector, options = } </i>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>AnnotationExporter.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>ReadCodebook.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Buttons.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>ReadCodebook.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Codebook.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>ReadCodebook.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Theme.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>Resume.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>Canvas.js</b>\n\n<i> </i>\n\n<i>e </i>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Alerts.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>FileUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>MoodleDownloadManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>URLUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>MoodleDownloadManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>ChromeStorage.js</b>\n\n<i>items </i>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>Codebook.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Theme.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>Codebook.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Config.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>Codebook.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>LanguageUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>oauth-client.js</b>\n\n<i>authRespListener event </i>\n\n<i>generateState  </i>\n\n<i>tokenInfoFrom response </i>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>RandomUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>Hypothesis.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>AnnotationServer.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>AnnotatedFileGeneration.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>TXT.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>UserFilter.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Events.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>UserFilter.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>LanguageUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>RandomUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>moodleAssignmentAddContentScript.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>background.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Popup.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>LanguageUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>MoodleComment.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Commenting.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>MoodleComment.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>MoodleClientManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>MoodleComment.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Events.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>MoodleComment.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>MoodleUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>AnnotationServerManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>contentScript.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>AnnotationBasedInitializer.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>contentScript.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>ContentScriptManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>CreateCodebook.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>HypothesisClientManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>scripts.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>args.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>PDFTextUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>Classifying.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Body.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>CodebookManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>CreateCodebook.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>CodebookManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>ReadCodebook.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>build.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>Task.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>RolesManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Config.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>ExportCodebookJSON.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Codebook.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>Annotation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>LanguageUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>default.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>MoodleEstimationManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>MoodleEstimation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>MoodleEstimationManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>DateTimeUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>MoodleEstimationManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Events.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>PDF.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>chromereload.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>args.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>AnnotationBasedInitializer.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>URLUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>AnnotationBasedInitializer.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Alerts.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>AnnotationBasedInitializer.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Config.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>Neo4JClient.js</b>\n\n<i>initializeGraph err, response </i>\n\n<i>descapalo data</i>\n\n<i>debuggingg msg, priority </i>\n\n<i>apiCall settings, callback </i>\n\n<i>escapalo data</i>\n\n<i>isString value </i>\n\n<i>escapify myJSON </i>\n\n<i>doNothing  }</i>\n\n<i>commitNeo4J query, callback </i>\n\n<i>sleep miliseconds </i>\n\n<i>traverse o </i>\n\n<i>randomString length = 17, charSet </i>\n\n<i>cypherRDFNeo4J cypher, callback </i>\n\n<i>getObjectId data, id </i>\n\n<i>apiCallJSON settings, callback </i>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>DeleteCodebook.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>UpdateAnnotation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Events.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>UpdateAnnotation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>LanguageUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>UpdateAnnotation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Alerts.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>UpdateAnnotation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Annotation.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>dom-anchor-text-quote.js</b>\n\n<i>toRange root, selector, options = } </i>\n\n<i>fromTextPosition root, selector </i>\n\n<i>fromRange root, range </i>\n\n<i>toTextPosition root, selector, options = } </i>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>BrowserStorageManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>ChromeStorage.js</b>\n\n<i>items </i>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>BrowserStorageManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>URLUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>BrowserStorageManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>BrowserStorageClient.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>BrowserStorageManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>AnnotationServerManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>MoodleBackgroundManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>ChromeStorage.js</b>\n\n<i>items </i>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>MoodleBackgroundManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>MoodleClient.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>MoodleBackgroundManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>MoodleFunctions.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>BrowserStorageSearch.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>BrowserStorageManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>BrowserStorageSearch.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>URLUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>BrowserStorageSearch.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Alerts.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>BrowserStorageSearch.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Config.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>applyBrowserPrefixesFor.js</b>\n\n<i>applyBrowserPrefixesFor _vendor </i>\n\n<i>iterator obj </i>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>ImportCodebook.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>ImportCodebookJSON.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>springerContentScript.js</b>\n\n<i>pdfLinkElement </i>\n\n<i>result, selector </i>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>URLUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>springerContentScript.js</b>\n\n<i>pdfLinkElement </i>\n\n<i>result, selector </i>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Config.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>TaskManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>ChromeStorage.js</b>\n\n<i>items </i>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>TaskManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>CreateHighlighterTask.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>TaskManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Config.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>BuiltIn.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>GroupInitializer.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>CreateHighlighterTask.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Task.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>CreateHighlighterTask.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>MoodleUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>CreateHighlighterTask.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>AnnotationUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>CreateHighlighterTask.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Codebook.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>CreateHighlighterTask.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>Config.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>MoodleUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>CryptoUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>TargetManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>MoodleScraping.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>moodleResumption.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>HypothesisClientManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>moodleResumption.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>BrowserStorageManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>moodleResumption.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>MoodleFunctions.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>moodleResumption.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>MoodleClientManager.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>moodleResumption.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>MoodleUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>content.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>args.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>images.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]-->[<b>args.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
[<b>URLUtils.js</b>\n\n variant:ConceptAndGo\n variant:HighlightAndGo\n variant:MarkAndGo\n variant:OATS\n variant:ReviewAndGo]
@enduml